// <auto-generated />
namespace Reporting_Assistant_New.ReportingMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsernameFinalComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsernameFinalComment));
        
        string IMigrationMetadata.Id
        {
            get { return "202006121326055_UsernameFinalComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
