// <auto-generated />
namespace Reporting_Assistant_New.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class birthdate_datetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(birthdate_datetime));
        
        string IMigrationMetadata.Id
        {
            get { return "202006060750582_birthdate_datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
